pub const FRONTAL_UPPER_LEG_WIDTH: f32 = 30.;
pub const FRONTAL_UPPER_LEG_BIG_HEIGHT: f32 = 3.5;
pub const FRONTAL_UPPER_LEG_SMALL_HEIGHT: f32 = 2.5;

pub const FRONTAL_MIDDLE_LEG_WIDTH: f32 = FRONTAL_UPPER_LEG_WIDTH * 0.60; // 3 / 5
pub const FRONTAL_MIDDLE_LEG_BIG_HEIGHT: f32 = FRONTAL_UPPER_LEG_BIG_HEIGHT * 0.60;
pub const FRONTAL_MIDDLE_LEG_SMALL_HEIGHT: f32 = FRONTAL_UPPER_LEG_SMALL_HEIGHT * 0.60;

pub const FRONTAL_BOTTOM_LEG_WIDTH: f32 = FRONTAL_MIDDLE_LEG_WIDTH * 0.33; // change from 24.
pub const FRONTAL_BOTTOM_LEG_HEIGHT: f32 = FRONTAL_MIDDLE_LEG_BIG_HEIGHT * 0.60; // change from 6.

pub const LEG_DEPTH: f32 = 3.25;
pub const MIDDLE_LEG_DEPTH: f32 = 2.;
pub const BASE_LEG_DEPTH: f32 = 1.5;

pub const DEFAULT_Z_NEAR: f32 = 1.;
pub const DEFAULT_Z_FAR: f32 = 300.;
pub const DEFAULT_FIELD_OF_VIEW_IN_RADIANS: f32 = 60.;

pub const INITIAL_LEG_DISPLACEMENT_X: f32 = 0.;
pub const INITIAL_LEG_DISPLACEMENT_Y: f32 = 0.;
pub const INITIAL_LEG_DISPLACEMENT_Z: f32 = -100.;

pub const INITIAL_BODY_DISPLACEMENT_X: f32 = 20.;
pub const INITIAL_BODY_DISPLACEMENT_Y: f32 = 0.;
pub const INITIAL_BODY_DISPLACEMENT_Z: f32 = -80.;






